-- 1
SELECT SHIPS.NAME, SHIPS.LAUNCHED, CLASSES.COUNTRY, CLASSES.NUMGUNS  FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS

-- 2 

-- 3
SELECT SHIP FROM OUTCOMES JOIN BATTLES ON BATTLE = NAME WHERE DATE LIKE "%1942%";

--4
SELECT * FROM SHIPS LEFT JOIN OUTCOMES ON NAME = SHIP WHERE BATTLE IS NULL;


